---
- name: Setup KVM on Rocky Linux
  hosts: all
  become: yes
  tasks:
    - name: Install necessary packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - qemu-kvm
        - libvirt
        - libvirt-client
        - bridge-utils
        - virt-install

    - name: Start and enable libvirtd service
      systemd:
        name: libvirtd
        enabled: yes
        state: started

    - name: Add user to kvm and libvirt groups
      user:
        name: "{{ ansible_user }}"
        groups: "kvm,libvirt"
        append: yes
